<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddGPTAction</name>
   <tag></tag>
   <elementGuidId>fa3aefbe-54f0-476f-8525-c345d8cdb478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv184']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv184' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv184</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add GPT Action&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv184</value>
      <webElementGuid>2e83260e-c40e-4f36-8f56-d2cf31195e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv184</value>
      <webElementGuid>8cf22624-fbb1-42b9-bada-cb5a089a220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='Add GPT Action']</value>
      <webElementGuid>89fd7212-41c5-4e16-809c-3accf57be966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>961ee08d-b21a-4348-85ff-19d09a2d0824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='fv184']</value>
      <webElementGuid>6bac7f1e-ac0a-4c8c-ac84-3f6bb529e740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon184']/button</value>
      <webElementGuid>2434cd10-2e83-4a0c-bf48-612b94598003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv184' and @type = 'button' and @name = 'fv184' and (text() = '</value>
      <webElementGuid>321b0d8e-bccc-4c3f-8548-97d595e8ef54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
