<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RemoveGPTAction</name>
   <tag></tag>
   <elementGuidId>d92c3bb2-20df-4d40-89fe-ed2316581db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv185']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv185' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv185</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;RemoveGPTAction&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv185</value>
      <webElementGuid>617f9b04-9539-4f1f-a301-63469855a2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv185</value>
      <webElementGuid>86ad3f4b-9997-4f30-a46d-4b95311be78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='RemoveGPTAction']</value>
      <webElementGuid>1d9b9a94-f0a3-43a9-b00a-52c3a5043e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>d7245014-0aba-4b63-9fae-e5bd3bb91765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon185']/button</value>
      <webElementGuid>7a2aba79-ce7f-43d0-8e9a-00d935a4275b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv185' and @type = 'button' and @name = 'fv185' and (text() = '&#xd;
				RemoveGPTAction&#xd;
			' or . = '&#xd;
				RemoveGPTAction&#xd;
			')]</value>
      <webElementGuid>4c417026-fb57-4816-85e1-1941899f0d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
