<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GoToWidgetToggle</name>
   <tag></tag>
   <elementGuidId>af825c6f-9dd3-4f4f-b96c-c7b1c747e717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv206']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv206' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv206</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go To Widget Toggle Tests&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv206</value>
      <webElementGuid>33c9e5bd-ec74-4641-9c4a-fb1c7803320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F206</value>
      <webElementGuid>fdce1965-07a3-4f3a-aec6-debea15ec982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Go To Widget Toggle Tests')]</value>
      <webElementGuid>12f7373e-d14c-474e-a8b0-cdea49d773ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>536172fe-fa49-49f6-8a05-f749440e8507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='fv206']</value>
      <webElementGuid>dce0839a-ea40-4c8d-9a8c-4df26d8be416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon206']/button</value>
      <webElementGuid>19920ce7-69e6-4ee2-bb95-1f3a657a53cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv206' and @type = 'button' and @name = 'F206' and (text() = '</value>
      <webElementGuid>d68ed39e-40a8-42c2-936f-e913f4274c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
