<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RemoveAllIntents</name>
   <tag></tag>
   <elementGuidId>8174a72d-49bc-4ac0-b100-6f0f236e30ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv148']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv148' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv148</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remove All Intents&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv148</value>
      <webElementGuid>eaf23e64-79c7-444e-af2f-ea201ca28f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv148</value>
      <webElementGuid>96ac6eed-2756-49d8-8243-6ec0ce2d1500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Remove All Intents')]</value>
      <webElementGuid>cb80f398-8186-4ebe-9fa2-e30590c5b00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>ba11912e-c5c0-444b-8302-a3d446256a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='fv148']</value>
      <webElementGuid>98b63d1c-744d-45f4-b93a-c8b740364d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon148']/button</value>
      <webElementGuid>659a398d-cd61-4a3b-a0c0-6bb0b72d69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv148' and @type = 'button' and @name = 'fv148' and (text() = '</value>
      <webElementGuid>cf16c318-ad28-41b2-9db5-98e5db431790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
