<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GetIntents</name>
   <tag></tag>
   <elementGuidId>ca68a57e-448e-455a-bea3-fe9da4a1c75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv147']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv147' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv147</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;GetIntents&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv147</value>
      <webElementGuid>1d0f1192-1d97-4110-baeb-5b3cfa241333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv147</value>
      <webElementGuid>8dc0f014-c178-4810-8099-991dc33a1778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'GetIntents')]</value>
      <webElementGuid>c32290f9-f30a-4e68-8e2f-0ee51aa6b663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>64a569a9-ff22-4e6d-b5a8-52465d752b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon147']/button</value>
      <webElementGuid>a4c9cd7c-c144-4fdc-8405-e9de148c5da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv147' and @type = 'button' and @name = 'fv147' and (text() = '</value>
      <webElementGuid>2f5c70a3-a9a7-4771-9c32-c3c1291a199c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
