<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GetIntents</name>
   <tag></tag>
   <elementGuidId>00eb8bc5-3acf-4d5f-aecc-520edca758b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fv149']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv149' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv149</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;GetIntents&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv149</value>
      <webElementGuid>5a66219c-91b6-479c-9e4e-f207bba75f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv149</value>
      <webElementGuid>bfd9ddf6-5601-421e-805f-799f5b84091c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='F149']/following-sibling::input</value>
      <webElementGuid>5a543237-3fd9-4843-8e9e-b831f217ce51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>d364e96e-7d5b-45fa-9d9f-8b732819e9da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='fv149']</value>
      <webElementGuid>810cf627-2295-490f-8c7f-cc40bb86fb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fv149' and @name = 'fv149']</value>
      <webElementGuid>207a56ef-3324-4ed0-90e1-00a3fa36a37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
