<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AI_container</name>
   <tag></tag>
   <elementGuidId>ac39d025-dc5e-4456-9b7f-12ae6cb1bf9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'panel-container')]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'panel-container')]/div</value>
      <webElementGuid>6704a4ce-f85b-4339-80ca-69faf5fb6256</webElementGuid>
   </webElementProperties>
</WebElementEntity>
