<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entities</name>
   <tag></tag>
   <elementGuidId>0452aac8-a7e8-4dfc-b62e-b7c40f65804f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fv195']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv195' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv195</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entities&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv195</value>
      <webElementGuid>699110d1-1c76-4304-8eb9-36c173ad3c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv195</value>
      <webElementGuid>a0f70507-fb6d-450f-81a3-33bb257d68d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='F195']/following-sibling::input</value>
      <webElementGuid>21a64c31-5b2f-4073-bf5d-8985da4ed8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>ea969256-1464-46ff-a33f-8f1c537f8e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='fv195']</value>
      <webElementGuid>5f639783-6e0b-473b-bde0-81c9f15f15ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fv195' and @name = 'fv195']</value>
      <webElementGuid>c5ca0c19-1d0c-4cfa-bb6d-009c2c707c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
