<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Actions_Icon</name>
   <tag></tag>
   <elementGuidId>92e05c74-e6e3-4c07-bcdd-2d92a83141f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarDropdown</value>
      <webElementGuid>66ba6033-2849-4454-9299-35bdcc6618b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>932aeee9-9819-4b45-9e0e-86efe052e355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>b3809b9e-9240-494f-b660-835ef4c75091</webElementGuid>
   </webElementProperties>
</WebElementEntity>
