<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First</name>
   <tag></tag>
   <elementGuidId>4ad4bf19-4dbf-4063-b954-46afd333dee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'First']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First</value>
      <webElementGuid>9160d3f9-fc95-4450-a9f8-7e9fce9c54c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbi___home</value>
      <webElementGuid>367a5ad4-de9c-47ac-ad99-c69420f2a82a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
