<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last</name>
   <tag></tag>
   <elementGuidId>c38ecd10-7039-4cdb-9f1c-6352d939de7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Last']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last</value>
      <webElementGuid>08a8bdd7-c2c4-4517-95f2-d116f2523e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbi___end</value>
      <webElementGuid>9299a961-ffa6-4cc5-bc6b-2cd6843ab456</webElementGuid>
   </webElementProperties>
</WebElementEntity>
