<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>location</name>
   <tag></tag>
   <elementGuidId>46e2e21d-f11a-4776-820f-7b84339e405c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-type='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-type='location']</value>
      <webElementGuid>754a6aa2-8e53-41e2-ad4e-df70fb0f697c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
