<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>conversation_container</name>
   <tag></tag>
   <elementGuidId>920faafb-aa82-4dc9-a018-897e15ce38d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'panel-container')]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'panel-container')]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'panel-container')]/div</value>
      <webElementGuid>7f80a08c-9ac6-4942-ae47-11f15a5a7551</webElementGuid>
   </webElementProperties>
</WebElementEntity>
