<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Campaign_Outer</name>
   <tag></tag>
   <elementGuidId>2bc73e31-45dc-4dfe-b0ea-49fbe3665d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ifFrontpage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifFrontpage</value>
      <webElementGuid>5f6778f9-7898-4ea9-a1e4-9e29fda04ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifFrontpage</value>
      <webElementGuid>881d0f38-b4a7-4318-af7d-e160b5ae2543</webElementGuid>
   </webElementProperties>
</WebElementEntity>
