<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RemoveAllCategories</name>
   <tag></tag>
   <elementGuidId>efbddfa6-cc75-4d33-a2fc-f98ed19423b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv166']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv166' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv166</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remove All Categories&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv166</value>
      <webElementGuid>2655342d-6203-4e41-8f20-d8db4a456258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv166</value>
      <webElementGuid>5efa13f3-6757-4a38-b52d-3fb9c04bc339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='Remove All Categories']</value>
      <webElementGuid>8dcf4033-d95e-4843-8c44-756e823bcadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>16a6021c-e156-4112-908d-30f31849b2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='fv166']</value>
      <webElementGuid>ffc9f4f4-54a3-4af8-b5b7-a6d42ba6af2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon166']/button</value>
      <webElementGuid>e2d155b2-6e9d-449d-bc79-b2d6cf2be313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv166' and @type = 'button' and @name = 'fv166' and (text() = '</value>
      <webElementGuid>c9fc2289-8297-47b1-bf38-b4ca72443b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
