<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GetCategories</name>
   <tag></tag>
   <elementGuidId>ec2e0dbd-b282-4893-85cb-50eefb3e43ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fv162']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv162' and @ref_element = 'Object Repository/AgentAssist/iframe_Campaign_Inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fv162</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;GetCategories&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv162</value>
      <webElementGuid>ad2e9697-4aec-4370-8439-2cc3058c3185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv162</value>
      <webElementGuid>a47af881-ff67-427e-b276-fc07c7f2d82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='GetCategories']</value>
      <webElementGuid>eb76f336-a148-4a65-9e14-808044985c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>729f7bb0-2aaf-40f9-9cc2-4109200db10c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='fv162']</value>
      <webElementGuid>30cca96d-3775-4a45-84f8-860efc0f0494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[@id='csCon162']/button</value>
      <webElementGuid>9c7f3ae3-1263-41fc-a765-1a0da1124b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id = 'fv162' and @type = 'button' and @name = 'fv162' and (text() = '</value>
      <webElementGuid>4f06a38b-7b0f-4177-856f-9af062f688a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
