<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Categories</name>
   <tag></tag>
   <elementGuidId>601e23f3-7bb8-49fe-8f77-71a9787f3e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fv163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fv163</value>
      <webElementGuid>5c53b155-727e-440c-a366-5b6fab1a1d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fv163</value>
      <webElementGuid>6d673d85-6c62-4343-9325-f45a3465150d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='F163']/following-sibling::input</value>
      <webElementGuid>d9641617-8a04-48e6-ad80-7ebd60631a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AgentAssistTest/AgentAssist/iframe_Campaign_Inner</value>
      <webElementGuid>07f6abf8-b949-47d1-9046-e2dbce6a3e1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
